### ISSUE TITLE
Acces Denied Error On local

### ISSUE THREAD

**Issue by ramazanbiyikqlub** [gentee/eonza#10]
2 things tried.
1-) 

- install eonza like document explain
- set host as localhost
- whitelist your local ip

    I got access denied error on trying 127.0.0.1:<port> or 0.0.0.0:<port>. Couldnt solve it so 2. way tried.

2-) 

- Do everything on 1. 
- Install nginx and do simple reverse proxy
        
        server {
         
        listen       80;

        listen       [::]:80;

        server_name  _;

        root         /usr/share/nginx/html;

        include /etc/nginx/default.d/*.conf;

        error_page 404 /404.html;
        location = /404.html {
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        }
        location / {
        proxy_pass http://localhost:3235;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Host "localhost";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP localhost;
        }
        }
    
    - I can get response from localhost:<port> 127.0.01:<port> and 0.0.0.0:<port>. So far so good.
    
    My remote machine is on aws btw. I set loadbalancer and target group. Set port as 80. Set route53. 
    And baam from outside to eonza gave access denied error again. 
    How can i solve it? 
    
    Eonza.yaml:
    
      mode: default
      assetsdir: ""
      packagesdir: ""
      log:
      dir: ""
      mode: file
      level: info
      users:
        dir: ""
      http:
        host: localhost
        port: 3235
        open: false
        theme: default
        #    cert: "/home/x/eonza/ssl/eonza.crt"
        #    priv: "/home/x/eonza/ssl/eonza.key"
        playground:
        dir: ""
        summary: 20000000
        files: 250
        size: 3000000
        tasks: 3
      whitelist:
        - ::1/128
        - 127.0.0.0/31
        - 10.0.0.0/24
        - localhost
        - 127.0.0.1`

**Comment by gentee** [comment]
You should add IP-address of your computer to the whitelist. If the internet provider changes IP addresses then add mask.
For example,

```yaml
  - 95.241.208.0/24
  - 95.241.209.0/24
  - 95.241.210.0/24
```

This means all ip-addresses from 95.241.208.0 to 95.241.210.255

**Comment by ramazanbiyikqlub** [comment]
And one more thing i have a vpn. Just need to find the correct ip address to add.
Just changed the last number with 0
For now i added those:

- ::1/128
- 127.0.0.0/31
- xxx.xxx.xxx.0/24 -> VPN server ip
- xxx.xxx.xxx.0/24 -> ISP public ip
- xxx.xxx.xxx+1.0/24 -> Above ip addres but 3. number is added 1.
- xxx.xxx.xxx.0/24 -> Eonza server ip address
- 10.0.0.0/16 -> aws vpc ip address

What i am doing wrong?

**Comment by ramazanbiyikqlub** [comment]
Checked nginx access logs.
My public ip is written there.
`x.x.x.x - - [19/Jan/2023:15:24:39 +0000] "GET / HTTP/1.1" 403 28 "-" "curl/7.79.1" "**ISP public Ip**"`

**Comment by gentee** [comment]
Where do you get Access denied error? In the browser?
What IPv4 address is shown on https://whatismyipaddress.com/ or some like service?
Specify it in eonza.yaml and restart eonza service. Don't restart eonza when you change eonza.yaml file.

**Comment by ramazanbiyikqlub** [comment]
On both browser and terminal (with curl)
So the network path is : 
Request goes to VPn server with my public ip.
VPN server calls the eonza service that in the same VPC.
I get my ip from https://www.whatismyip.com/

**Comment by gentee** [comment]
Unfortunately, I cannot resolve your problem. I have not installed Eonza on cloud services and used it through VPN. Try not to specify whitelist but switch on two-factor authentification.

**Comment by ramazanbiyikqlub** [comment]
Is there a way to allow all the ips? 0.0.0.0/0 is not working.

**Comment by gentee** [comment]
Delete "whitelist:" with ips in the config file.

**Comment by ramazanbiyikqlub** [comment]
- create ssl keys (no need to be verified)
- Enter your hostname on eonza.yaml (like eonza.tes.test)
- Create https protocol on tg (this was that i missed)
