### ISSUE TITLE
Исчезли мои данные с адреса https://www.eonza.com/mulkaro/#

### ISSUE THREAD

**Issue by mulkaro** [gentee/eonza#3]
Отображается ошибка "Page not found: The requested page has not been found on this server. It could have been deleted, moved or you could have mistyped the address in your browser.".

Хотя месяц назад просматривал свои данные.

**Comment by gentee** [comment]
Внёс исправления. Попробуйте сейчас. У меня по крайней мере страница login открывается. 
Мы еще год назад всех уведомляли, что закрываем сервис по бесплатному хостингу старого проекта Eonza.
Данные все остались и мы вам можем их выслать или сами сделайте backup средствами программы.
В общем, подумайте насчёт переноса данных, а то в конце концов, может вообще всё быть удалено, так как проект по размещению пользователей закрыт.

**Comment by mulkaro** [comment]
Теперь заработало. Спасибо. А что это было?

**Comment by mulkaro** [comment]
Я понял, подумаю. Сделаю backup и решу перенос данных.
 
Спасибо за оперативность.
  
>Воскресенье, 25 апреля 2021, 4:58 +03:00 от Alexey Krivonogov ***@***.***>:
> 
> 
>Внёс исправления. Попробуйте сейчас. У меня по крайней мере страница login открывается.
>Мы еще год назад всех уведомляли, что закрываем сервис по бесплатному хостингу старого проекта Eonza.
>Данные все остались и мы вам можем их выслать или сами сделайте backup средствами программы.
>В общем, подумайте насчёт переноса данных, а то в конце концов, может вообще всё быть удалено, так как проект по размещению пользователей закрыт.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
----------------------------------------------------------------------
С уважением
Юрий

**Comment by gentee** [comment]
> Теперь заработало. Спасибо. А что это было?

Мы специально не удаляем то, что было, но сам домен уже используется для других целей. Поэтому могут происходить накладки в работе сервера из-за новых настроек.
